/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/chris.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chris.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat20} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat23} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat22} />
      <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat17} />
      <mesh geometry={nodes['Node-Mesh_4'].geometry} material={materials.mat8} />
    </group>
  )
}

useGLTF.preload('/chris.glb')
